services:
  frontend:
    restart: always
    build:
      context: .
      dockerfile: ./front.dockerfile
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    ports:
      - 5009:5009
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: .
      dockerfile: ./back.dockerfile
    env_file:
      - ./backend/.env
    environment:
      # These will be loaded from backend/.env
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASS}
      - MYSQL_DB=${MYSQL_DB}
      - PORT=${PORT}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    volumes:
      - ./backend/src:/app/src
    ports:
      - 5008:5008